Admin/Multi-Language.MVCClient/Controllers/MultiLanguage/ContextsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Multi_language.Data;
using Multi_language.Models;
using Multi_language.Services;
using AutoMapper.QueryableExtensions;
using Multi_Language.MVCClient.Models;
using AutoMapper;
using Microsoft.AspNet.Identity;

namespace Multi_Language.MVCClient.Controllers
{
    public class ContextsController : BaseController
    {
        private IPhrasesContextServices contextServices;
        public ContextsController(IPhrasesContextServices contextServices)
        {
            this.contextServices = contextServices;
        }
        // GET: Contexts
        public ActionResult Index()
        {
            var model = contextServices.GetAllByIdProject(UserActiveProject, User.Identity.GetUserId()).ProjectTo<PhrasesContextViewModel>();

            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "All added contexts", "Add context and then you can add translations.");
            if (Request.IsAjaxRequest())
                return PartialView(model);

            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Add new context", "Short description");
            if (Request.IsAjaxRequest())
                return PartialView();

            return View();
        }

        [HttpPost]
        public ActionResult Create(PhrasesContextViewModel model)
        {
            if (!ModelState.IsValid)
            {
                Response.Headers["InvalidModel"] = "false";

                SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Add new context", "You have some validation errors.");
                if (Request.IsAjaxRequest())
                    return PartialView(model);

                return View(model);
            }
            if (User.Identity.GetActiveProject() == "0")
            {
                SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Add new language", "You have to create project first.");
                ModelState.AddModelError("", "Create your first project and then you can add contexts.");
                if (Request.IsAjaxRequest())
                    return PartialView(model);

                return View(model);
            }
            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "All added context", "New context is created successfully.");

            model.DateChanged = DateTime.Now;
            model.DateCreated = DateTime.Now;
            model.UserId = User.Identity.GetUserId();
            model.IdProject = UserActiveProject;
            contextServices.Add(Mapper.Map<PhrasesContext>(model));

            if (Request.IsAjaxRequest())
                return PartialView("Index", contextServices.GetAllByIdProject(UserActiveProject, User.Identity.GetUserId()).ProjectTo<PhrasesContextViewModel>());

            return View("Index", contextServices.GetAllByIdProject(UserActiveProject, User.Identity.GetUserId()).ProjectTo<PhrasesContextViewModel>());
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue)
            {
                SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Edit context", "Error. Go back to list and choose context.");
                return View(new PhrasesContextViewModel());
            }
            var idLang = id ?? 0;
            var model = Mapper.Map<PhrasesContextViewModel>(contextServices.GetById(idLang));

            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Edit context", " ");
            if (Request.IsAjaxRequest())
                return PartialView(model);

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(PhrasesContextViewModel model)
        {
            if (!ModelState.IsValid)
            {
                SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Edit", "You have some validation errors.");
                if (Request.IsAjaxRequest())
                    return PartialView(model);

                return View(model);
            }
            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "All added context", "Context is edited successfully.");

            model.DateChanged = DateTime.Now;
            model.UserId = User.Identity.GetUserId();

            contextServices.Update(Mapper.Map<PhrasesContext>(model));

            if (Request.IsAjaxRequest())
                return PartialView("Index", contextServices.GetAllByIdProject(UserActiveProject, User.Identity.GetUserId()).ProjectTo<PhrasesContextViewModel>());

            return View("Index", contextServices.GetAllByIdProject(UserActiveProject, User.Identity.GetUserId()).ProjectTo<PhrasesContextViewModel>());
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Details for context", "Error. Go back to list and choose context.");
                return View(new PhrasesContextViewModel());
            }
            var idLang = id ?? 0;
            var model = Mapper.Map<PhrasesContextViewModel>(contextServices.GetById(idLang));

            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Details for context", " ");
            if (Request.IsAjaxRequest())
                return PartialView(model);

            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Delete context", "Error. Go back to list and choose context.");
                return View(new PhrasesContextViewModel());
            }
            var idLang = id ?? 0;
            var model = Mapper.Map<PhrasesContextViewModel>(contextServices.GetById(idLang));

            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Delete context", "Alert! All contexts and resources associate with the context will be deleted to!");
            if (Request.IsAjaxRequest())
                return PartialView(model);

            return View(model);
        }

        // POST: Contexts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            contextServices.Delete(id);
            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "All added context", "Context is deleted successfully.");

            if (Request.IsAjaxRequest())
                return PartialView("Index", contextServices.GetAllByIdProject(UserActiveProject, User.Identity.GetUserId()).ProjectTo<PhrasesContextViewModel>());

            return View("Index", contextServices.GetAllByIdProject(UserActiveProject, User.Identity.GetUserId()).ProjectTo<PhrasesContextViewModel>());
        }

    }
}

Admin/Multi-Language.MVCClient/Views/Contexts/Create.cshtml
@model Multi_Language.MVCClient.Models.PhrasesContextViewModel

@{
    ViewBag.Title = "Create";
}
<!-- Default box -->
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Create new</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">

@using (Ajax.RawAjaxBeginForm("fa-cube","Create","Contexts", null, new AjaxOptions {}, null))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Context, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Context, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Context, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

  </div>
    <!-- /.box-body -->
    <div class="box-footer">
     @Ajax.RawActionLinkWithoutIcon("Back to list", "fa-cube", "Index", "Contexts", null, new AjaxOptions { }, null)
    </div>
    <!-- /.box-footer-->
</div>
<!-- /.box -->

Admin/Multi-Language.MVCClient/Views/Contexts/Delete.cshtml
@model Multi_Language.MVCClient.Models.PhrasesContextViewModel

    @{
        ViewBag.Title = "Delete";
    }
<!-- Default box -->
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Delete</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Context)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Context)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateChanged)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateChanged)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DateCreated)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DateCreated)
            </dd>

        </dl>


    </div>
          </div>
    <!-- /.box-body -->
    <div class="box-footer">
       @using (Ajax.RawAjaxBeginForm("fa-cube","Delete","Contexts",   new {  id=Model.IdPhraseContext }, new AjaxOptions {}, null))
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
           @Ajax.RawActionLinkWithoutIcon("Back to list", "fa-cube", "Index", "Contexts", null, new AjaxOptions { }, null)
            </div>
        }
    </div>
    <!-- /.box-footer-->
</div>
<!-- /.box -->

Admin/Multi-Language.MVCClient/Views/Contexts/Details.cshtml
@model Multi_Language.MVCClient.Models.PhrasesContextViewModel

@{
    ViewBag.Title = "Details";
}


<!-- Default box -->
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Details</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Context)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Context)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateChanged)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateChanged)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

    </dl>
</div>
</div>
    <!-- /.box-body -->
    <div class="box-footer">
      @Ajax.RawActionLinkWithoutIcon("Edit", "fa-cube", "Edit", "Contexts", new { id = Model.IdPhraseContext }, new AjaxOptions { }, new { @class = "" })

    |
    @Ajax.RawActionLinkWithoutIcon("Back to list", "fa-cube", "Index", "Contexts", null, new AjaxOptions { }, null)

    </div>
    <!-- /.box-footer-->
</div>
<!-- /.box -->

Admin/Multi-Language.MVCClient/Views/Contexts/Edit.cshtml
@model Multi_Language.MVCClient.Models.PhrasesContextViewModel
@{
    ViewBag.Title = "Edit";
}

<!-- Default box -->
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Edit </h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">

@using (Ajax.RawAjaxBeginForm("fa-cube","Edit","Contexts",   new {  id=Model.IdPhraseContext }, new AjaxOptions {}, null))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPhraseContext)
        @Html.HiddenFor(model => model.DateCreated)
        @Html.HiddenFor(model => model.IdProject)

        <div class="form-group">
            @Html.LabelFor(model => model.Context, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Context, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Context, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
</div>
    <!-- /.box-body -->
    <div class="box-footer">
     @Ajax.RawActionLinkWithoutIcon("Back to list", "fa-cube", "Index", "Contexts", null, new AjaxOptions { }, null)
    </div>
    <!-- /.box-footer-->
</div>
<!-- /.box -->

Admin/Multi-Language.MVCClient/Views/Contexts/Index.cshtml
@model IEnumerable<Multi_Language.MVCClient.Models.PhrasesContextViewModel>

@{
    ViewBag.Title = "Index";
}

<!-- Default box -->
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Current contexts - @Model.Count()</h3>

        <div class="box-tools pull-right">
            @Ajax.RawActionLinkWithoutIcon("Create New", "fa-cube", "Create", "Contexts",
           null, new AjaxOptions { }, new { @class = "btn btn-success btn-xs" })


            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <table class="table table-bordered table-hover table-striped dataTable">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IdPhraseContext)
                    </th>
                    <th>
                        User Name
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Context)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateChanged)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateCreated)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IdPhraseContext)
                    </th>
                    <th>
                        User Name
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Context)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateChanged)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DateCreated)
                    </th>
                    <th></th>
                </tr>
            </tfoot>
            <tbody>
                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdPhraseContext)
                        </td>
                        <td>
                            <button class="btn btn-primary btn-xs"
                                    data-toggle="collapse" data-target="#show-@item.IdPhraseContext" aria-expanded="false" aria-controls="show-@item.IdPhraseContext">
                                SHOW
                            </button>

                            <div class="collapse" id="show-@item.IdPhraseContext">
                                <div class="well">
                                    @Html.DisplayFor(modelItem => item.User.UserName)

                                </div>
                            </div>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Context)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateChanged)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DateCreated)
                        </td>
                        <td>
                            <div class="btn-group-sm  pull-right">
                                @{
                                    var url = System.Configuration.ConfigurationManager.AppSettings["MultiLanguageApiUrl"];
                                    url = url + "/Project/" + item.IdProject + "/Context/" + item.IdPhraseContext;
                                }
                                 <a href="@url" title="Open link" target="_blank" class="btn btn-info btn-xs">Go to URL</a>

                                @Ajax.RawActionLinkWithoutIcon("Details", "fa-cube", "Details", "Contexts",
                               new { id = item.IdPhraseContext }, new AjaxOptions { }, new { @class = "btn btn-default btn-xs" })

                                @Ajax.RawActionLinkWithoutIcon("Edit", "fa-cube", "Edit", "Contexts",
                               new { id = item.IdPhraseContext }, new AjaxOptions { }, new { @class = "btn btn-default btn-xs" })

                                @Ajax.RawActionLinkWithoutIcon("Delete", "fa-cube", "Delete", "Contexts",
                               new { id = item.IdPhraseContext }, new AjaxOptions { }, new { @class = "btn btn-default btn-xs" })
                            </div>
                        </td>

                    </tr>
                                    }
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
    <div class="box-footer">

        <p>
            @Ajax.RawActionLinkWithoutIcon("Create New", "fa-cube", "Create", "Contexts", null, new AjaxOptions { }, new { @class = "btn btn-success btn-flat" })
        </p>
    </div>
    <!-- /.box-footer-->
</div>
<!-- /.box -->