Admin/Multi-Language.MVCClient/Models/UtilitiesViewModels/BackupViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Multi_language.Common.Infrastructure.Mapping;
using Multi_Language.MVCClient.ApiInfrastructure.ApiModels;

namespace Multi_Language.MVCClient.Models.UtilitiesViewModels
{
    public class BackupViewModel : IMapFrom<BackupApiModel>
    {
        public string FileName { get; set; }

        public string FileSize { get; set; }

    }


}

Admin/Multi-Language.MVCClient/Controllers/Utilities/BackupsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Multi_Language.MVCClient.ApiInfrastructure;
using Multi_Language.MVCClient.Models.UtilitiesViewModels;
using Multi_language.ApiHelper;
using Multi_language.ApiHelper.Client;
using Multi_Language.MVCClient.ApiInfrastructure.Client;
using Newtonsoft.Json;
using AutoMapper;
using Multi_Language.MVCClient.Attributes;

namespace Multi_Language.MVCClient.Controllers.Utilities
{
    [Authentication]
    public class BackupsController : BaseController
    {
        private readonly ITokenContainer tokenContainer;
        private readonly IBackupClient backupClient;
        public BackupsController(ITokenContainer tokenContainer, IBackupClient backupClient)
        {
            this.tokenContainer = tokenContainer;
            this.backupClient = backupClient;
        }
        public async Task<ActionResult> Index()
        {
            var backups = await backupClient.GetBackups();
            var model = new List<BackupViewModel>();
            foreach (var backupApiModel in backups.Data)
            {
                model.Add(Mapper.Map<BackupViewModel>(backupApiModel));
            }
            SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Backups page", "Create, upload and restore the DataBase");
            if (Request.IsAjaxRequest())
                return PartialView(model);

            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> CreateBackup(string suffix = "")
        {
            if (!Request.IsAjaxRequest())
            {
                var result = new { Success = "False", Message = "Not authorized!" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            var backups = await backupClient.CreateBackup(suffix);
            var model = Mapper.Map<BackupViewModel>(backups.Data);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteBackup(string fileName)
        {
            if (!Request.IsAjaxRequest() || String.IsNullOrWhiteSpace(fileName) || tokenContainer.ApiToken == null)
            {
                var result = new { Success = "False", Message = "Not authorized!" };
                return Json(result, JsonRequestBehavior.AllowGet);
            }

            var backups = await backupClient.DeleteBackup(fileName);
            var model = Mapper.Map<BackupViewModel>(backups.Data);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        //// GET: Backup
        //public ActionResult Index()
        //{
        //    var model = new List<BackupViewModels>();
        //    try
        //    {
        //        using (HttpClient client = new HttpClient())
        //        {
        //            var bearerToken = tokenContainer.ApiToken.ToString();
        //            // TODO Add validation for bearer token

        //            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", bearerToken);
        //            ViewBag.BearerToken = bearerToken;
        //            var response = client.GetAsync(ConfigurationManager.AppSettings["MultiLanguageApiUrl"] + "/backup/getall").GetAwaiter().GetResult();
        //            if (response.IsSuccessStatusCode)
        //            {
        //                var result = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
        //                model = JsonConvert.DeserializeObject<List<BackupViewModels>>(result);
        //            }
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        //TODO send to admin or do something with this
        //    }

        //    SetViewBagsAndHeaders(Request.IsAjaxRequest(), "Backups page", "Create, upload and restore the DataBase");
        //    if (Request.IsAjaxRequest())
        //        return PartialView(model);

        //    return View(model);
        //}

    }
}

Admin/Multi-Language.MVCClient/Views/Backups/Index.cshtml
@using System.Data.Entity.Core.Mapping
@model IEnumerable<Multi_Language.MVCClient.Models.UtilitiesViewModels.BackupViewModel>
@{
    ViewBag.Title = "Backups Page";
}
<!-- Default box -->
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title">Current backups - <span id="backups-counter">@Model.Count()</span></h3>

        <div class="box-tools pull-right">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#backupModal">
                Create Backup
            </button>
            <button type="button" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#uploadBackupModal">
                Upload Backup
            </button>



            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <table class="table table-bordered table-hover table-striped dataTable">
            <thead>
                <tr>
                    <th>
                        File name
                    </th>
                    <th>
                        File size
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>
                        File name
                    </th>
                    <th>
                        File size
                    </th>
                    <th></th>
                </tr>
            </tfoot>
            <tbody>
                @{
                    int counter = 0;
                }
                @foreach (var item in Model)
            {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FileName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FileSize)
                        </td>
                        <td>
                            <div class="btn-group-sm  pull-right">

                                <button class="btn btn-success btn-xs" onclick="DownloadBackup(this,  '@item.FileName')">
                                    Download
                                </button>

                                <button class="btn btn-primary btn-xs"
                                        data-toggle="collapse" data-target="#restore-@counter" aria-expanded="false" aria-controls="restore-@counter">
                                    Restore
                                </button>
                                <button class="btn btn-danger btn-xs"
                                        data-toggle="collapse" data-target="#delete-@counter" aria-expanded="false" aria-controls="delete-@counter">
                                    Delete
                                </button>
                            </div>
                            <div class="clearfix"></div>
                            <div class="collapse" id="restore-@counter">
                                <div class="well">
                                    Every change after this backup will be lost. Please confirm:
                                    <div class="btn-group-sm">
                                        <button class="btn btn-default btn-xs"
                                                data-toggle="collapse" data-target="#restore-@counter" aria-expanded="false" aria-controls="restore-@counter">
                                            CLOSE
                                        </button>
                                        <button class="btn btn-primary btn-xs" onclick="RestoreBackup(this, '@item.FileName')"
                                                data-toggle="collapse" data-target="#restore-@counter" aria-expanded="false" aria-controls="restore-@counter">
                                            CONFIRM
                                        </button>

                                    </div>

                                </div>
                            </div>

                            <div class="collapse" id="delete-@counter">
                                <div class="well">
                                    Are you sure you want to delete this backup? Please confirm:
                                    <div class="btn-group-sm">
                                        <button class="btn btn-default btn-xs"
                                                data-toggle="collapse" data-target="#delete-@counter" aria-expanded="false" aria-controls="delete-@counter">
                                            CLOSE
                                        </button>
                                        @Ajax.ActionLink("CONFIRM", "DeleteBackup", "Backups", new { fileName = item.FileName },
                               new AjaxOptions
                               {
                                   HttpMethod = "POST",
                                   OnComplete = "DeleteBackup(this)"
                               }, new { @class = "btn btn-danger btn-xs", data_toggle = "collapse", data_target = "#delete-" + counter, aria_expanded = "false", aria_controls = "delete-" + counter })


                                    </div>

                                </div>
                            </div>
                        </td>

                    </tr>
                    counter++;
                }
            </tbody>

        </table>


    </div>
    <div class="overlay" id="loading-overlay" style="display: none"><i class="fa fa-refresh fa-spin"></i></div>

    <!-- /.box-body -->
    <div class="box-footer">

        <p class="col-md-4">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-success btn-flat" data-toggle="modal" data-target="#backupModal">
                Create Backup
            </button>
            <button type="button" class="btn btn-warning btn-flat" data-toggle="modal" data-target="#uploadBackupModal">
                Upload Backup
            </button>

        </p>


        <div class="alert alert-success alert-dismissible col-md-6 pull-right" role="alert" id="restore-alert-success" style="display: none">
            <button type="button" class="close" onclick="DissmisAlerRestore()"><span aria-hidden="true">&times;</span></button>
            <strong>Success!</strong> Database restored successfully.
        </div>

    </div>
    <!-- /.box-footer-->
</div>
<!-- /.box -->
<!-- Modal -->
<div class="modal fade modal-success" id="backupModal" tabindex="-1" role="dialog" aria-labelledby="backupModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="backupModalLabel">Create new backup</h4>
            </div>
            <div class="modal-body">
                <h5>
                    Add suffix to backup name.
                </h5>
                <label for="suffix">Template used for name:</label>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-suffix">{ComputerName_AppName_Version_Date_Hour_Suffix}</span>
                    <input type="text" class="form-control" id="suffix" aria-describedby="basic-suffix">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-outline" data-dismiss="modal" onclick="CreateBackup(this)">Save changes</button>

            </div>
        </div>
    </div>
</div>

<div class="modal fade modal-warning" id="uploadBackupModal" tabindex="-1" role="dialog" aria-labelledby="uploadBackupModal-label">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="uploadBackupModal-label">Upload backups - you can restore db even from different PC</h4>
            </div>
            <div class="modal-body">
                <input id="input-backups" name="input-backups" type="file" multiple class="file-loading">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
                @*<button type="button" class="btn btn-outline" data-dismiss="modal" onclick="UploadBackup(this)">Save changes</button>*@
            </div>
        </div>
    </div>
</div>
<script>
    var baseAdressApi = '@System.Configuration.ConfigurationManager.AppSettings["MultiLanguageApiUrl"]';

    function CreateBackup(elem) {
        var url = '../../Backups/CreateBackup';
        $.ajax({
            url: url,
            type: 'POST',
            data: { suffix: $('#suffix').val() },
            dataType: 'json',
            success: function (data, textStatus, xhr) {
                $('.sidebar-menu li a:contains("Backups")').click();
            },
            error: function (xhr, textStatus, errorThrown) {
                alert(xhr.responseText);
            }
        });
    };

    function DeleteBackup(elem) {
        var parent = $(elem).parents().eq(4);

        //TODO get and show false response

        $("#backups-counter").text($("#backups-counter").text() - 1);
        $(parent).hide(300,
            function () {
                // TODO REFRESH datatable in some way
            });
        //alert(xhr.responseText);
        //$(parent).fadeTo(100, 1);
    };

    function DownloadBackup(elem, fileName) {
        var url = baseAdressApi + '/backup/download/' + fileName + '/';

        document.getElementById('file-download-frame').src = url;
    };

    function RestoreBackup(elem, fileName) {
        var url = baseAdressApi + '/backup/restore/' + fileName + '/';

        $("#loading-overlay").slideDown(100, function () {
            $.ajax({
                url: url,
                type: 'POST',
                dataType: 'json',
                success: function (data, textStatus, xhr) {
                    $("#loading-overlay").slideUp(100);
                    $("#restore-alert-success").slideDown(300);
                },
                error: function (xhr, textStatus, errorThrown) {
                    alert(xhr.responseText);
                    $("#loading-overlay").slideUp(100);
                }
            });
        });
    };

    function DissmisAlerRestore() {
        $("#restore-alert-success").slideUp(300);

    };
</script>